# Generated by Django 5.1.3 on 2024-12-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qtxt', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=100)),
                ('op1', models.CharField(max_length=100)),
                ('op2', models.CharField(max_length=100)),
                ('op3', models.CharField(max_length=100)),
                ('op4', models.CharField(max_length=100)),
                ('sub', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('percentag', models.IntegerField()),
                ('login_date', models.IntegerField()),
            ],
            options={
                'db_table': 'result',
            },
        ),
    ]
